fix: command should use exit instead of return, return will not break

diff --git a/commands/build b/commands/build
--- a/commands/build
+++ b/commands/build
@@ -11,13 +11,19 @@ core() {
     exit 0
   fi
 
-  log::info "################## Building ##################"
+  log::info "################## BUILD START ##################"
+  
   pipeline::build
-  log::info "################ Building END ################"
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to build."
+    exit 1
+  fi
+
+  log::info "################ BUILD END ################"
 }
 
 run() {
-  core $@
+  core "$@"
 }
 
-run $@
+run "$@"
diff --git a/commands/checkout b/commands/checkout
--- a/commands/checkout
+++ b/commands/checkout
@@ -11,9 +11,15 @@ core() {
     exit 0
   fi
 
-  log::info "################## Checking out ##################"
+  log::info "################## CHECKOUT START ##################"
+
   pipeline::checkout
-  log::info "################ Checking out END ################"
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to checkout"
+    exit 1
+  fi
+
+  log::info "################ CHECKOUT END ################"
 }
 
 run() {
diff --git a/commands/deploy b/commands/deploy
--- a/commands/deploy
+++ b/commands/deploy
@@ -11,7 +11,15 @@ core() {
     exit 0
   fi
 
+  log::info "################## DEPLOY START ##################"
+
   pipeline::deploy
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to deploy."
+    exit 1
+  fi
+
+  log::info "################ DEPLOY END ################"
 }
 
 run() {
