feat: checkout support \$HOME/.git-credentials, build/deploy support \$HOME/.docker/config.json

diff --git a/core/checkout b/core/checkout
--- a/core/checkout
+++ b/core/checkout
@@ -2,21 +2,6 @@
 
 # pipeline::checkout - Git clone and checkout a branch of a repository
 pipeline::checkout() {
-  if [ -z "$CI_GIT_SERVER" ]; then
-    log::error "[pipeline::checkout] env CI_GIT_SERVER is required"
-    exit 1
-  fi
-
-  if [ -z "$CI_GIT_USERNAME" ]; then
-    log::error "[pipeline::checkout] env CI_GIT_USERNAME is required"
-    exit 1
-  fi
-
-  if [ -z "$CI_GIT_TOKEN" ]; then
-    log::error "[pipeline::checkout] env CI_GIT_TOKEN is required"
-    exit 1
-  fi
-
   if [ -z "$CI_GIT_COMMIT_HASH" ]; then
     log::error "[pipeline::checkout] env CI_GIT_COMMIT_HASH is required"
     exit 1
@@ -32,11 +17,29 @@ pipeline::checkout() {
     exit 1
   fi
 
-  log::info "[pipeline::checkout] login git server($CI_GIT_SERVER) ..."
-  login::git $CI_GIT_SERVER $CI_GIT_USERNAME $CI_GIT_TOKEN
-  if [ "$?" != "0" ]; then
-    log::error "[pipeline::checkout] failed to login git server($CI_GIT_SERVER)."
-    return 1
+  local git_credentials_path=$HOME/.git-credentials
+  if [ ! -f "$git_credentials_path" ]; then
+    if [ -z "$CI_GIT_SERVER" ]; then
+      log::error "[pipeline::checkout] env CI_GIT_SERVER is required"
+      exit 1
+    fi
+
+    if [ -z "$CI_GIT_USERNAME" ]; then
+      log::error "[pipeline::checkout] env CI_GIT_USERNAME is required"
+      exit 1
+    fi
+
+    if [ -z "$CI_GIT_TOKEN" ]; then
+      log::error "[pipeline::checkout] env CI_GIT_TOKEN is required"
+      exit 1
+    fi
+
+    log::info "[pipeline::checkout] login git server($CI_GIT_SERVER) ..."
+    login::git $CI_GIT_SERVER $CI_GIT_USERNAME $CI_GIT_TOKEN
+    if [ "$?" != "0" ]; then
+      log::error "[pipeline::checkout] failed to login git server($CI_GIT_SERVER)."
+      return 1
+    fi
   fi
 
   log::info "[pipeline::checkout] checkouting $CI_GIT_REPOSITORY at commit $CI_GIT_COMMIT_HASH ..."
diff --git a/core/deploy b/core/deploy
--- a/core/deploy
+++ b/core/deploy
@@ -12,16 +12,6 @@ pipeline::deploy() {
     return 1
   fi
 
-  if [ -z "$CI_IMAGE_USERNAME" ]; then
-    log::error "[pipeline::deploy] env CI_IMAGE_USERNAME is required"
-    return 1
-  fi
-
-  if [ -z "$CI_IMAGE_TOKEN" ]; then
-    log::error "[pipeline::deploy] env CI_IMAGE_TOKEN is required"
-    return 1
-  fi
-
   if [ -z "$CI_GIT_COMMIT_HASH" ]; then
     log::error "[pipeline::deploy] env CI_GIT_COMMIT_HASH is required"
     return 1
@@ -44,11 +34,24 @@ pipeline::deploy() {
 
   cd $CI_GIT_WORKDIR
 
-  log::info "[pipeline::deploy] login image server($CI_IMAGE_SERVER) ..."
-  login::docker $CI_IMAGE_SERVER $CI_IMAGE_USERNAME $CI_IMAGE_TOKEN
-  if [ "$?" != "0" ]; then
-    log::error "[pipeline::deploy] failed to login image server($CI_GIT_SERVER)."
-    return 1
+  local docker_config_path=$HOME/.docker/config.json
+  if [ ! -f "$docker_config_path" ]; then
+    if [ -z "$CI_IMAGE_USERNAME" ]; then
+      log::error "[pipeline::build] env CI_IMAGE_USERNAME is required"
+      return 1
+    fi
+
+    if [ -z "$CI_IMAGE_TOKEN" ]; then
+      log::error "[pipeline::build] env CI_IMAGE_TOKEN is required"
+      return 1
+    fi
+
+    log::info "[pipeline::build] login image server($CI_IMAGE_SERVER) ..."
+    login::docker $CI_IMAGE_SERVER $CI_IMAGE_USERNAME $CI_IMAGE_TOKEN
+    if [ "$?" != "0" ]; then
+      log::error "[pipeline::build] failed to login image server($CI_GIT_SERVER)."
+      return 1
+    fi
   fi
 
   local image_tag=commit_$CI_GIT_COMMIT_HASH
