feat: support deploy command based on service

diff --git a/core/docker_deploy b/core/docker_deploy
--- a/core/docker_deploy
+++ b/core/docker_deploy
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-pipeline::docker_deploy() {
+pipeline::docker_deploy_v0() {
   local name=$1
   local config=$2
 
@@ -71,7 +71,7 @@ pipeline::docker_deploy() {
     if [ "$key" = "CI_NETWORK" ]; then
       network=$value
     fi
-  done < "$config"
+  done <"$config"
 
   if [ -z "$image" ]; then
     log::error "[pipeline::docker_deploy] image is required"
@@ -84,5 +84,42 @@ pipeline::docker_deploy() {
 
   build_scripts="$build_scripts $image"
 }
+
+pipeline::docker_deploy() {
+  log::info "[pipeline::docker_deploy] checking ..."
+
+  local PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME=${PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME:-$PIPELINE_SERVICE_INSTANCE_NAME}
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME" ]; then
+    log::error "[pipeline::docker_deploy] PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME is required"
+    exit 1
+  fi
+
+  local PLUGIN_PIPELINE_SERVICE_DIR=$PLUGIN_PIPELINE_SERVICE_CONTEXT_BASE/$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME
+  if [ ! -d "$PLUGIN_PIPELINE_SERVICE_DIR" ]; then
+    log::error "[pipeline::docker_deploy] PLUGIN_PIPELINE_SERVICE_DIR($PLUGIN_PIPELINE_SERVICE_DIR) is not found"
+    exit 1
+  fi
+
+  local PIPELINE_SERVICE_ENV_FILE=$PLUGIN_PIPELINE_SERVICE_DIR/.env
+  if [ ! -f "$PIPELINE_SERVICE_ENV_FILE" ]; then
+    log::error "[pipeline::docker_deploy] PIPELINE_SERVICE_ENV_FILE($PIPELINE_SERVICE_ENV_FILE) is not found"
+    exit 1
+  fi
+
+  log::info "[pipeline::docker_deploy] preparing ..."
+  pipeline::service_prepare
+
+  log::info "[pipeline::docker_deploy] starting ..."
+
+  pipeline::service_start
+  if [ $? -ne 0 ]; then
+    log::error "[pipeline::docker_deploy] pipeline::service_start failed"
+    exit 1
+  fi
+
+  log::success "[pipeline::docker_deploy] success ..."
+}
+
+export -f pipeline::docker_deploy_v0
 
 export -f pipeline::docker_deploy
diff --git a/core/service_prepare b/core/service_prepare
--- a/core/service_prepare
+++ b/core/service_prepare
@@ -1,48 +1,65 @@
 #!/bin/bash
 
 pipeline::service_prepare() {
-  local context=$1
-  if [ -z "$context" ]; then
-    context=$PWD
+  export PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME=${PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME:-$PIPELINE_SERVICE_INSTANCE_NAME}
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME" ]; then
+    log::error "service name(PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME) is required"
+    exit 1
   fi
 
   # Network
-  docker network inspect $PLUGIN_PIPELINE_NETWORK >> /dev/null 2>&1
+  docker network inspect $PLUGIN_PIPELINE_NETWORK >>/dev/null 2>&1
   if [ "$?" != "0" ]; then
-    docker network create $PLUGIN_PIPELINE_NETWORK >> /dev/null 2>&1
+    docker network create $PLUGIN_PIPELINE_NETWORK >>/dev/null 2>&1
   fi
 
-  local dockerfile_path=$context/Dockerfile
-  local dotenv_path=$context/.env
-  local zmicro_rc=$context/.zmicrorc
-  if [ ! -f "$dockerfile_path" ]; then
-    log::error "Dockerfile not found"
+  export PLUGIN_PIPELINE_SERVICE_CONTEXT=${PLUGIN_PIPELINE_SERVICE_CONTEXT_BASE}/$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME
+  export PLUGIN_PIPELINE_SERVICE_DIR=$PLUGIN_PIPELINE_SERVICE_CONTEXT
+  export PLUGIN_PIPELINE_SERVICE_ENV_FILE=$PLUGIN_PIPELINE_SERVICE_CONTEXT/.env
+  if [ ! -f "$PLUGIN_PIPELINE_SERVICE_ENV_FILE" ]; then
+    log::error ".env($PLUGIN_PIPELINE_SERVICE_ENV_FILE) not found"
     exit 1
   fi
 
-  if [ ! -f "$dotenv_path" ]; then
-    log::error ".env not found"
-    exit 1
-  fi
-
-  if [ ! -f "$zmicro_rc" ]; then
-    log::error ".zmicrorc not found"
-    exit 1
-  fi
-
-  # @TODO
-  # config::export $PLUGIN_PIPELINE_MOD
+  # load mod
   config::load_file $PLUGIN_PIPELINE_MOD
   export PLUGIN_NAME=$PLUGIN_NAME
   export PLUGIN_VERSION=$PLUGIN_VERSION
   export PLUGIN_DESCRIPTION=$PLUGIN_DESCRIPTION
 
-  # load .zmicrorc
-  config::load_file $zmicro_rc
+  # load PLUGIN_PIPELINE_SERVICE_ENV_FILE
+  config::load_file $PLUGIN_PIPELINE_SERVICE_ENV_FILE
 
-  export PLUGIN_PIPELINE_CONTEXT=$context
-  export PLUGIN_PIPELINE_ENV_FILE=$dotenv_path
-  export PLUGIN_PIPELINE_NAME=$PIPELINE_NAME
+  ###
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_IMAGE_NAME" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_IMAGE_NAME is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_IMAGE_VERSION" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_IMAGE_VERSION is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_IMAGE_AUTHOR" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_IMAGE_AUTHOR is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_INSTANCE_NAME is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_PIPELINE_SERVICE_INSTANCE_UUID" ]; then
+    log::error "PLUGIN_PIPELINE_SERVICE_INSTANCE_UUID is required"
+    exit 1
+  fi
 }
 
 export -f pipeline::service_prepare
