fix: PLUGIN_PIPELINE_BUILD_ID

diff --git a/core/environment b/core/environment
--- a/core/environment
+++ b/core/environment
@@ -3,6 +3,11 @@
 pipeline::env() {
   # BUILD CONTEXT FILES
 
+  if [ -z "$PIPELINE_BUILD_CONTEXT" ]; then
+    log::error "[pipeline::env] PIPELINE_BUILD_CONTEXT is required"
+    exit 1
+  fi
+
   # build env
   export PIPELINE_BUILD_CONTEXT_ENV="$PLUGIN_PIPELINE_BUILD_CONTEXT/env"
 
@@ -25,14 +30,14 @@ pipeline::env() {
   pipeline::env_save
 
   # log
-  log::info "PIPELINE_BUILD_ID: $PIPELINE_BUILD_ID"
-  log::info "PIPELINE_BUILD_CONTEXT: $PIPELINE_BUILD_CONTEXT"
-  log::info "PIPELINE_BUILD_CONTEXT_ENV: $PIPELINE_BUILD_CONTEXT_ENV"
+  log::info "PIPELINE_BUILD_ID: $PLUGIN_PIPELINE_BUILD_ID"
+  log::info "PIPELINE_BUILD_CONTEXT: $PLUGIN_PIPELINE_BUILD_CONTEXT"
+  # log::info "PIPELINE_BUILD_CONTEXT_ENV: $PIPELINE_BUILD_CONTEXT_ENV"
   log::info "PIPELINE_BUILD_CONTEXT_LOG: $PIPELINE_BUILD_CONTEXT_LOG"
-  log::info "PIPELINE_BUILD_CONTEXT_STATUS: $PIPELINE_BUILD_CONTEXT_STATUS"
-  log::info "PIPELINE_BUILD_CONTEXT_RUNNING_AT: $PIPELINE_BUILD_CONTEXT_RUNNING_AT"
-  log::info "PIPELINE_BUILD_CONTEXT_SUCCEED_AT: $PIPELINE_BUILD_CONTEXT_SUCCEED_AT"
-  log::info "PIPELINE_BUILD_CONTEXT_FAILED_AT: $PIPELINE_BUILD_CONTEXT_FAILED_AT"
+  # log::info "PIPELINE_BUILD_CONTEXT_STATUS: $PIPELINE_BUILD_CONTEXT_STATUS"
+  # log::info "PIPELINE_BUILD_CONTEXT_RUNNING_AT: $PIPELINE_BUILD_CONTEXT_RUNNING_AT"
+  # log::info "PIPELINE_BUILD_CONTEXT_SUCCEED_AT: $PIPELINE_BUILD_CONTEXT_SUCCEED_AT"
+  # log::info "PIPELINE_BUILD_CONTEXT_FAILED_AT: $PIPELINE_BUILD_CONTEXT_FAILED_AT"
 }
 
 pipeline::env_save() {
